title: Randy Ramos
#logo: /assets/img/headshot_circle.png
#logo: /images/myHeadshot.jpg
logo: /images/myHeadshot_circle.png
description: Quality Engineer - SDET
#show_dowloads: true
theme: jekyll-theme-minimal
